/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videorentalstore.gui;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import videorentalstore.database.Database;

/**
 *
 * @author Ashley
 */
public class Account_SignIn extends javax.swing.JFrame {
    private Database db;
    /**
     * Creates new form Account_SignIn
     */
    public Account_SignIn(Database db) {
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInPanel = new javax.swing.JPanel();
        employee = new javax.swing.JButton();
        signinInfoPanel = new javax.swing.JPanel();
        rental4uLogoPanel = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        signInInfoPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        signinButton = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        signInLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        notAMemberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        setResizable(false);

        signInPanel.setBackground(new java.awt.Color(153, 0, 0));
        signInPanel.setPreferredSize(new java.awt.Dimension(1777, 1000));

        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        signinInfoPanel.setBackground(new java.awt.Color(153, 0, 0));

        rental4uLogoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_Rent4ULogoLarge.jpg"))); // NOI18N

        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        signInInfoPanel.setBackground(new java.awt.Color(153, 0, 0));
        signInInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username:");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");

        signinButton.setText("Sign In");
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });

        signInLabel.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setText("Sign In");

        javax.swing.GroupLayout signInInfoPanelLayout = new javax.swing.GroupLayout(signInInfoPanel);
        signInInfoPanel.setLayout(signInInfoPanelLayout);
        signInInfoPanelLayout.setHorizontalGroup(
            signInInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signInInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInInfoPanelLayout.createSequentialGroup()
                        .addComponent(signInLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addGroup(signInInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInInfoPanelLayout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInInfoPanelLayout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addGap(18, 18, 18)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(signinButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        signInInfoPanelLayout.setVerticalGroup(
            signInInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInInfoPanelLayout.createSequentialGroup()
                .addComponent(signInLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signInInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(signInInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(31, 31, 31)
                .addComponent(signinButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomeLabel.setText("Join Us And Rent Great Movies For Great Prices");

        notAMemberLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        notAMemberLabel.setText("Not a member?");

        javax.swing.GroupLayout signinInfoPanelLayout = new javax.swing.GroupLayout(signinInfoPanel);
        signinInfoPanel.setLayout(signinInfoPanelLayout);
        signinInfoPanelLayout.setHorizontalGroup(
            signinInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinInfoPanelLayout.createSequentialGroup()
                .addGroup(signinInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(signinInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinInfoPanelLayout.createSequentialGroup()
                                .addComponent(signInInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addComponent(rental4uLogoPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(signinInfoPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(notAMemberLabel)
                        .addGap(35, 35, 35)
                        .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        signinInfoPanelLayout.setVerticalGroup(
            signinInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinInfoPanelLayout.createSequentialGroup()
                .addComponent(rental4uLogoPanel)
                .addGap(31, 31, 31)
                .addComponent(welcomeLabel)
                .addGap(51, 51, 51)
                .addComponent(signInInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(signinInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpButton)
                    .addComponent(notAMemberLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(employee)
                .addGap(307, 307, 307)
                .addComponent(signinInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 697, Short.MAX_VALUE))
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(signinInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(400, 400, 400))
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(employee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        String email = usernameTxt.getText();
        char[] pw = passwordTxt.getPassword(); //gets password as char array
        String p = new String(pw); // converts char array to string
        
        try {
            if(db.isUser(email,p)) { //if username and password matches database take user to user profile
                if(db.isEmloyee(email)) {
                    dispose();
                    System.out.println("Employee Account page");
                    EmployeeAccount f = new EmployeeAccount(db);
                    f.setVisible(true);
                }
                else {
                    dispose();
                    System.out.println("Customer Account Page");
                    CustomerAccount_Movies f = new CustomerAccount_Movies(db);
                    f.setVisible(true);
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Your username and password do not match our database", "Username & Passeword", JOptionPane.ERROR_MESSAGE); //if password is wrong bring up error alert box
            }
        } catch (Exception ex) {
            Logger.getLogger(Account_SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signinButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        dispose();
        CustomerAccount_SignUp f = new CustomerAccount_SignUp(db);
        f.setVisible(true);
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        dispose();
        EmployeeAccount_SignUp f = new EmployeeAccount_SignUp(db);
        f.setVisible(true);
    }//GEN-LAST:event_employeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account_SignIn(db).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employee;
    private javax.swing.JLabel notAMemberLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel rental4uLogoPanel;
    private javax.swing.JPanel signInInfoPanel;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JButton signinButton;
    private javax.swing.JPanel signinInfoPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
