/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videorentalstore.gui;

import videorentalstore.User.User;
import videorentalstore.database.Database;

/**
 *
 * @author Ashley
 */
public class CustomerAccount_MyAccount extends javax.swing.JFrame {
    private Database db;
    private User currentUser;
    /**
     * Creates new form CustomerAccount_MyAccount
     */
    public CustomerAccount_MyAccount(Database db, User currentUser) {
        initComponents();
        this.db = db;
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyAccountPanel = new javax.swing.JPanel();
        personalInfoPanel4 = new javax.swing.JPanel();
        personalInfoLabel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        personalInfoTxtPanel = new javax.swing.JPanel();
        newUserEmailTxt1 = new javax.swing.JTextField();
        newUserEmailLabel1 = new javax.swing.JLabel();
        lastNameLabel2 = new javax.swing.JLabel();
        firstNameTxt2 = new javax.swing.JTextField();
        birthdayLabel2 = new javax.swing.JLabel();
        newUserPasswordLabel1 = new javax.swing.JLabel();
        newUserPasswordTxt1 = new javax.swing.JPasswordField();
        newUsernameLabel1 = new javax.swing.JLabel();
        firstNameLabel2 = new javax.swing.JLabel();
        newUsernameTxt1 = new javax.swing.JTextField();
        lastNameTxt2 = new javax.swing.JTextField();
        editBillingButton1 = new javax.swing.JButton();
        submitBillingButton1 = new javax.swing.JButton();
        birthdayTxtPanel = new javax.swing.JPanel();
        birthdayMonth = new javax.swing.JComboBox();
        birthdayYear = new javax.swing.JComboBox();
        birthdayDay = new javax.swing.JComboBox();
        billingInfoPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        billingInfoTxtPnel = new javax.swing.JPanel();
        editBillingButton = new javax.swing.JButton();
        addressTxt2 = new javax.swing.JTextField();
        creditCardExpLabel1 = new javax.swing.JLabel();
        submitBillingButton = new javax.swing.JButton();
        creditCardExpirationMonth = new javax.swing.JComboBox();
        zipcodeTxt2 = new javax.swing.JTextField();
        creditCardImage = new javax.swing.JLabel();
        cityTxt2 = new javax.swing.JTextField();
        creditCardExpirationYear = new javax.swing.JComboBox();
        creditCardNumTxt2 = new javax.swing.JTextField();
        creditCardNumLabel2 = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        stateLabel2 = new javax.swing.JLabel();
        zipcodeLabel2 = new javax.swing.JLabel();
        cityLabel2 = new javax.swing.JLabel();
        billingInformation_State_Combobox = new javax.swing.JComboBox();
        sideBarPanel = new javax.swing.JPanel();
        rentalsRULogoSmallLabel = new javax.swing.JLabel();
        blackBarPanel = new javax.swing.JPanel();
        viewPaymentHistoryToolBar = new javax.swing.JToolBar();
        viewRentalHistoryToolBar = new javax.swing.JToolBar();
        deleteAccountToolBar = new javax.swing.JToolBar();
        sideBarInfoPanel = new javax.swing.JPanel();
        viewPaymentHistoryToolBar1 = new javax.swing.JToolBar();
        ViewPaymentHistoryButton = new javax.swing.JButton();
        accountInfoToolBar = new javax.swing.JToolBar();
        AccountInfoButton = new javax.swing.JButton();
        viewRentalHistoryToolBar1 = new javax.swing.JToolBar();
        viewRentalHistoryButton = new javax.swing.JButton();
        deleteAccountToolBar1 = new javax.swing.JToolBar();
        deleteMyAcountButton = new javax.swing.JButton();
        toolBar = new javax.swing.JToolBar();
        homeButton = new javax.swing.JButton();
        divider1 = new javax.swing.JLabel();
        myAccountButton = new javax.swing.JButton();
        divider2 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        accountInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));

        MyAccountPanel.setBackground(new java.awt.Color(255, 255, 255));
        MyAccountPanel.setMaximumSize(new java.awt.Dimension(1800, 100));
        MyAccountPanel.setName(""); // NOI18N
        MyAccountPanel.setPreferredSize(new java.awt.Dimension(18000, 1000));

        personalInfoPanel4.setBackground(new java.awt.Color(255, 255, 255));
        personalInfoPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        personalInfoLabel4.setBackground(new java.awt.Color(153, 0, 0));

        jLabel20.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Personal Information");

        javax.swing.GroupLayout personalInfoLabel4Layout = new javax.swing.GroupLayout(personalInfoLabel4);
        personalInfoLabel4.setLayout(personalInfoLabel4Layout);
        personalInfoLabel4Layout.setHorizontalGroup(
            personalInfoLabel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoLabel4Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 915, Short.MAX_VALUE))
        );
        personalInfoLabel4Layout.setVerticalGroup(
            personalInfoLabel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoLabel4Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        personalInfoTxtPanel.setBackground(new java.awt.Color(255, 255, 255));

        newUserEmailTxt1.setForeground(new java.awt.Color(255, 255, 255));

        newUserEmailLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        newUserEmailLabel1.setText("Email:");

        lastNameLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        lastNameLabel2.setText("Last Name:");

        birthdayLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        birthdayLabel2.setText("Birthday:");

        newUserPasswordLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        newUserPasswordLabel1.setText("Password:");

        newUsernameLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        newUsernameLabel1.setText("Username:");

        firstNameLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        firstNameLabel2.setText("First Name:");

        editBillingButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_EditButtonIcon.png"))); // NOI18N
        editBillingButton1.setText("Edit");
        editBillingButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBillingButton1ActionPerformed(evt);
            }
        });
        editBillingButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editBillingButton1KeyPressed(evt);
            }
        });

        submitBillingButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_AddButtonIcon.png"))); // NOI18N
        submitBillingButton1.setText("Submit");

        birthdayTxtPanel.setBackground(new java.awt.Color(255, 255, 255));

        birthdayMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        birthdayYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "Item 1", "Item 2", "Item 3", "Item 4" }));

        birthdayDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout birthdayTxtPanelLayout = new javax.swing.GroupLayout(birthdayTxtPanel);
        birthdayTxtPanel.setLayout(birthdayTxtPanelLayout);
        birthdayTxtPanelLayout.setHorizontalGroup(
            birthdayTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdayTxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(birthdayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(birthdayDay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(birthdayYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        birthdayTxtPanelLayout.setVerticalGroup(
            birthdayTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdayTxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(birthdayTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout personalInfoTxtPanelLayout = new javax.swing.GroupLayout(personalInfoTxtPanel);
        personalInfoTxtPanel.setLayout(personalInfoTxtPanelLayout);
        personalInfoTxtPanelLayout.setHorizontalGroup(
            personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(newUserEmailLabel1)
                                        .addComponent(newUsernameLabel1))
                                    .addGap(25, 25, 25))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoTxtPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(firstNameLabel2)
                                    .addGap(18, 18, 18)))
                            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(birthdayLabel2)
                                .addGap(37, 37, 37)))
                        .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdayTxtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                    .addComponent(firstNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lastNameLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(lastNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                    .addComponent(newUsernameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(newUserPasswordLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(newUserPasswordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(newUserEmailTxt1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitBillingButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBillingButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        personalInfoTxtPanelLayout.setVerticalGroup(
            personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newUserPasswordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newUserPasswordLabel1))
                    .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newUsernameTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newUsernameLabel1)))
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(newUserEmailLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoTxtPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newUserEmailTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel2)
                    .addComponent(firstNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel2)
                    .addComponent(lastNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(birthdayTxtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(editBillingButton1)
                        .addGap(18, 18, 18)
                        .addComponent(submitBillingButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(birthdayLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout personalInfoPanel4Layout = new javax.swing.GroupLayout(personalInfoPanel4);
        personalInfoPanel4.setLayout(personalInfoPanel4Layout);
        personalInfoPanel4Layout.setHorizontalGroup(
            personalInfoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalInfoLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personalInfoTxtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        personalInfoPanel4Layout.setVerticalGroup(
            personalInfoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanel4Layout.createSequentialGroup()
                .addComponent(personalInfoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(personalInfoTxtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        billingInfoPanel1.setBackground(new java.awt.Color(255, 255, 255));
        billingInfoPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        billingInfoPanel1.setForeground(new java.awt.Color(51, 51, 51));
        billingInfoPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));

        jLabel6.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Billing information");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        billingInfoTxtPnel.setBackground(new java.awt.Color(255, 255, 255));

        editBillingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_EditButtonIcon.png"))); // NOI18N
        editBillingButton.setText("Edit");
        editBillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBillingButtonActionPerformed(evt);
            }
        });
        editBillingButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editBillingButtonKeyPressed(evt);
            }
        });

        addressTxt2.setForeground(new java.awt.Color(255, 255, 255));

        creditCardExpLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        creditCardExpLabel1.setText("Credit Card Expiration Date:");

        submitBillingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_AddButtonIcon.png"))); // NOI18N
        submitBillingButton.setText("Submit");

        creditCardExpirationMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        creditCardImage.setForeground(new java.awt.Color(255, 255, 255));
        creditCardImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashley\\Desktop\\movieprojectphotos\\Image_CreditCards.png")); // NOI18N

        cityTxt2.setForeground(new java.awt.Color(255, 255, 255));

        creditCardExpirationYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        creditCardNumTxt2.setForeground(new java.awt.Color(255, 255, 255));

        creditCardNumLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        creditCardNumLabel2.setText("Credit Card Number: ");

        addressLabel2.setBackground(new java.awt.Color(43, 45, 44));
        addressLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        addressLabel2.setText("Address:");

        stateLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        stateLabel2.setText("State:");

        zipcodeLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        zipcodeLabel2.setText("Zipcode:");

        cityLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        cityLabel2.setText("City:");

        billingInformation_State_Combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "AK - Alaska", "AL - Alabama", "AR - Arkansas", "AZ - Arizona", "CA - California", "CO - Colorado", "CT - Connecticut", "DE - Delaware", "FL - Florida", "GA - Georgia", "HI - Hawaii", "IA - Iowa", "ID - Idaho", "IL - Illinois", "IN -Indiana", "KS - Kansas", "KY - Kentucky", "LA - Louisiana", "MA - Massachusetts", "MD - Maryland", "ME - Maine", "MI - Michigan", "MN - Minnesota", "MO - Missouri", "MS - Mississippi", "MT - Montana", "NC - North Carolina", "ND - North Dakota", "NE - Nebraska", "NH - New Hampshire", "NJ - New Jersey", "NM - New Mexico", "NV - Nevada", "NY - New York", "OH - Ohio", "OK - Oklahoma", "OR - Oregon", "PA - Pennsylvania", "RI - Rhode Island", "SC - South Carolina", "SD - South Dakota", "TN - Tennessee", "TX - Texas", "UT - Utah", "VA - Virginia", "VT - Vermont", "WA - Washington", "WI - Wisconsin", "WV - West Virginia", "WY - Wyoming" }));
        billingInformation_State_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingInformation_State_ComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout billingInfoTxtPnelLayout = new javax.swing.GroupLayout(billingInfoTxtPnel);
        billingInfoTxtPnel.setLayout(billingInfoTxtPnelLayout);
        billingInfoTxtPnelLayout.setHorizontalGroup(
            billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingInfoTxtPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitBillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                        .addComponent(creditCardNumLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                                .addComponent(creditCardImage)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(creditCardNumTxt2)))
                    .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                            .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressLabel2)
                                .addComponent(cityLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                                    .addComponent(cityTxt2)
                                    .addGap(18, 18, 18)
                                    .addComponent(stateLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(billingInformation_State_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(zipcodeLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(zipcodeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(addressTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                            .addComponent(creditCardExpLabel1)
                            .addGap(29, 29, 29)
                            .addComponent(creditCardExpirationMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(creditCardExpirationYear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editBillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        billingInfoTxtPnelLayout.setVerticalGroup(
            billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateLabel2)
                            .addComponent(zipcodeLabel2)
                            .addComponent(zipcodeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel2)
                            .addComponent(billingInformation_State_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(creditCardNumLabel2)
                        .addComponent(creditCardNumTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(creditCardImage)
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditCardExpirationMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditCardExpirationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditCardExpLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingInfoTxtPnelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBillingButton)
                        .addGap(18, 18, 18)
                        .addComponent(submitBillingButton)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout billingInfoPanel1Layout = new javax.swing.GroupLayout(billingInfoPanel1);
        billingInfoPanel1.setLayout(billingInfoPanel1Layout);
        billingInfoPanel1Layout.setHorizontalGroup(
            billingInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingInfoPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(billingInfoTxtPnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        billingInfoPanel1Layout.setVerticalGroup(
            billingInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingInfoPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(billingInfoTxtPnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sideBarPanel.setBackground(new java.awt.Color(153, 0, 0));

        rentalsRULogoSmallLabel.setBackground(new java.awt.Color(153, 0, 0));
        rentalsRULogoSmallLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_Rent4ULogoSmall.jpg"))); // NOI18N

        blackBarPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout blackBarPanelLayout = new javax.swing.GroupLayout(blackBarPanel);
        blackBarPanel.setLayout(blackBarPanelLayout);
        blackBarPanelLayout.setHorizontalGroup(
            blackBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        blackBarPanelLayout.setVerticalGroup(
            blackBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        viewPaymentHistoryToolBar.setBackground(new java.awt.Color(153, 0, 0));
        viewPaymentHistoryToolBar.setBorder(null);
        viewPaymentHistoryToolBar.setFloatable(false);
        viewPaymentHistoryToolBar.setRollover(true);
        viewPaymentHistoryToolBar.setBorderPainted(false);

        viewRentalHistoryToolBar.setBorder(null);
        viewRentalHistoryToolBar.setFloatable(false);
        viewRentalHistoryToolBar.setForeground(new java.awt.Color(255, 255, 255));
        viewRentalHistoryToolBar.setRollover(true);
        viewRentalHistoryToolBar.setBorderPainted(false);

        deleteAccountToolBar.setBorder(null);
        deleteAccountToolBar.setFloatable(false);
        deleteAccountToolBar.setForeground(new java.awt.Color(255, 255, 255));
        deleteAccountToolBar.setRollover(true);
        deleteAccountToolBar.setBorderPainted(false);

        sideBarInfoPanel.setBackground(new java.awt.Color(153, 0, 0));

        viewPaymentHistoryToolBar1.setBackground(new java.awt.Color(153, 0, 0));
        viewPaymentHistoryToolBar1.setBorder(null);
        viewPaymentHistoryToolBar1.setFloatable(false);
        viewPaymentHistoryToolBar1.setRollover(true);
        viewPaymentHistoryToolBar1.setBorderPainted(false);

        ViewPaymentHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewPaymentHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewPaymentHistoryButton.setText("View Payment History");
        ViewPaymentHistoryButton.setFocusPainted(false);
        ViewPaymentHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPaymentHistoryButtonActionPerformed(evt);
            }
        });
        viewPaymentHistoryToolBar1.add(ViewPaymentHistoryButton);

        accountInfoToolBar.setBackground(new java.awt.Color(153, 0, 0));
        accountInfoToolBar.setBorder(null);
        accountInfoToolBar.setFloatable(false);
        accountInfoToolBar.setRollover(true);
        accountInfoToolBar.setBorderPainted(false);

        AccountInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountInfoButton.setText("Account Information");
        AccountInfoButton.setFocusPainted(false);
        AccountInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfoButtonActionPerformed(evt);
            }
        });
        accountInfoToolBar.add(AccountInfoButton);

        viewRentalHistoryToolBar1.setBorder(null);
        viewRentalHistoryToolBar1.setFloatable(false);
        viewRentalHistoryToolBar1.setForeground(new java.awt.Color(255, 255, 255));
        viewRentalHistoryToolBar1.setRollover(true);
        viewRentalHistoryToolBar1.setBorderPainted(false);

        viewRentalHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewRentalHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        viewRentalHistoryButton.setText("View Rental History");
        viewRentalHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRentalHistoryButtonActionPerformed(evt);
            }
        });
        viewRentalHistoryToolBar1.add(viewRentalHistoryButton);

        deleteAccountToolBar1.setBorder(null);
        deleteAccountToolBar1.setFloatable(false);
        deleteAccountToolBar1.setForeground(new java.awt.Color(255, 255, 255));
        deleteAccountToolBar1.setRollover(true);
        deleteAccountToolBar1.setBorderPainted(false);

        deleteMyAcountButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteMyAcountButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteMyAcountButton.setText("Delete My Account");
        deleteMyAcountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMyAcountButtonActionPerformed(evt);
            }
        });
        deleteAccountToolBar1.add(deleteMyAcountButton);

        javax.swing.GroupLayout sideBarInfoPanelLayout = new javax.swing.GroupLayout(sideBarInfoPanel);
        sideBarInfoPanel.setLayout(sideBarInfoPanelLayout);
        sideBarInfoPanelLayout.setHorizontalGroup(
            sideBarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarInfoPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(sideBarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountInfoToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarInfoPanelLayout.createSequentialGroup()
                        .addGroup(sideBarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteAccountToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewRentalHistoryToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(viewPaymentHistoryToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        sideBarInfoPanelLayout.setVerticalGroup(
            sideBarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(accountInfoToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(viewPaymentHistoryToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(viewRentalHistoryToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(deleteAccountToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentalsRULogoSmallLabel)
                            .addComponent(viewPaymentHistoryToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewRentalHistoryToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(deleteAccountToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sideBarInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 32, Short.MAX_VALUE)
                .addComponent(blackBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rentalsRULogoSmallLabel)
                .addGap(70, 70, 70)
                .addComponent(viewPaymentHistoryToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(viewRentalHistoryToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBarInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(501, 501, 501)
                .addComponent(deleteAccountToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
            .addComponent(blackBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        toolBar.setBackground(new java.awt.Color(255, 255, 255));
        toolBar.setBorder(null);
        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setBorderPainted(false);

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorderPainted(false);
        homeButton.setFocusable(false);
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        toolBar.add(homeButton);

        divider1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divider1.setText("  |  ");
        toolBar.add(divider1);

        myAccountButton.setBackground(new java.awt.Color(255, 255, 255));
        myAccountButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myAccountButton.setText("My Account");
        myAccountButton.setFocusable(false);
        myAccountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myAccountButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        myAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccountButtonActionPerformed(evt);
            }
        });
        toolBar.add(myAccountButton);

        divider2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divider2.setText("  |  ");
        toolBar.add(divider2);

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        toolBar.add(logoutButton);

        accountInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_AccountInformationLabel.png"))); // NOI18N

        javax.swing.GroupLayout MyAccountPanelLayout = new javax.swing.GroupLayout(MyAccountPanel);
        MyAccountPanel.setLayout(MyAccountPanelLayout);
        MyAccountPanelLayout.setHorizontalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billingInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personalInfoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(accountInfoLabel)
                        .addGap(680, 680, 680)
                        .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2047, Short.MAX_VALUE))
        );
        MyAccountPanelLayout.setVerticalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountInfoLabel)
                            .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addComponent(personalInfoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(billingInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1829, Short.MAX_VALUE))
        );

        getContentPane().add(MyAccountPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBillingButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBillingButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBillingButton1ActionPerformed

    private void editBillingButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editBillingButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBillingButton1KeyPressed

    private void editBillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBillingButtonActionPerformed

    }//GEN-LAST:event_editBillingButtonActionPerformed

    private void editBillingButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editBillingButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBillingButtonKeyPressed

    private void billingInformation_State_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingInformation_State_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingInformation_State_ComboboxActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        dispose();
        CustomerAccount_Movies f = new CustomerAccount_Movies(db, currentUser);
        f.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void myAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountButtonActionPerformed
        dispose();
        CustomerAccount_MyAccount f = new CustomerAccount_MyAccount(db, currentUser);
        f.setVisible(true);
    }//GEN-LAST:event_myAccountButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        dispose();
        Account_SignIn f = new Account_SignIn(db);
        f.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ViewPaymentHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPaymentHistoryButtonActionPerformed
        dispose();
        CustomerAccount_PaymentHistory f = new CustomerAccount_PaymentHistory(db, currentUser);
        f.setVisible(true);
    }//GEN-LAST:event_ViewPaymentHistoryButtonActionPerformed

    private void AccountInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfoButtonActionPerformed
        dispose();
        CustomerAccount_MyAccount f = new CustomerAccount_MyAccount(db, currentUser);
        f.setVisible(true);
    }//GEN-LAST:event_AccountInfoButtonActionPerformed

    private void viewRentalHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRentalHistoryButtonActionPerformed
        dispose();
        CustomerAccount_RentalHistory f = new CustomerAccount_RentalHistory(db, currentUser);
        f.setVisible(true);
    }//GEN-LAST:event_viewRentalHistoryButtonActionPerformed

    private void deleteMyAcountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMyAcountButtonActionPerformed
        dispose();
        CustomerAccount_DeleteAccount f = new CustomerAccount_DeleteAccount(db, currentUser);
        f.setVisible(true);
    }//GEN-LAST:event_deleteMyAcountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAccount_MyAccount(db, currentUser).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountInfoButton;
    private javax.swing.JPanel MyAccountPanel;
    private javax.swing.JButton ViewPaymentHistoryButton;
    private javax.swing.JLabel accountInfoLabel;
    private javax.swing.JToolBar accountInfoToolBar;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JTextField addressTxt2;
    private javax.swing.JPanel billingInfoPanel1;
    private javax.swing.JPanel billingInfoTxtPnel;
    private javax.swing.JComboBox billingInformation_State_Combobox;
    private javax.swing.JComboBox birthdayDay;
    private javax.swing.JLabel birthdayLabel2;
    private javax.swing.JComboBox birthdayMonth;
    private javax.swing.JPanel birthdayTxtPanel;
    private javax.swing.JComboBox birthdayYear;
    private javax.swing.JPanel blackBarPanel;
    private javax.swing.JLabel cityLabel2;
    private javax.swing.JTextField cityTxt2;
    private javax.swing.JLabel creditCardExpLabel1;
    private javax.swing.JComboBox creditCardExpirationMonth;
    private javax.swing.JComboBox creditCardExpirationYear;
    private javax.swing.JLabel creditCardImage;
    private javax.swing.JLabel creditCardNumLabel2;
    private javax.swing.JTextField creditCardNumTxt2;
    private javax.swing.JToolBar deleteAccountToolBar;
    private javax.swing.JToolBar deleteAccountToolBar1;
    private javax.swing.JButton deleteMyAcountButton;
    private javax.swing.JLabel divider1;
    private javax.swing.JLabel divider2;
    private javax.swing.JButton editBillingButton;
    private javax.swing.JButton editBillingButton1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JTextField firstNameTxt2;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JTextField lastNameTxt2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myAccountButton;
    private javax.swing.JLabel newUserEmailLabel1;
    private javax.swing.JTextField newUserEmailTxt1;
    private javax.swing.JLabel newUserPasswordLabel1;
    private javax.swing.JPasswordField newUserPasswordTxt1;
    private javax.swing.JLabel newUsernameLabel1;
    private javax.swing.JTextField newUsernameTxt1;
    private javax.swing.JPanel personalInfoLabel4;
    private javax.swing.JPanel personalInfoPanel4;
    private javax.swing.JPanel personalInfoTxtPanel;
    private javax.swing.JLabel rentalsRULogoSmallLabel;
    private javax.swing.JPanel sideBarInfoPanel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel stateLabel2;
    private javax.swing.JButton submitBillingButton;
    private javax.swing.JButton submitBillingButton1;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JToolBar viewPaymentHistoryToolBar;
    private javax.swing.JToolBar viewPaymentHistoryToolBar1;
    private javax.swing.JButton viewRentalHistoryButton;
    private javax.swing.JToolBar viewRentalHistoryToolBar;
    private javax.swing.JToolBar viewRentalHistoryToolBar1;
    private javax.swing.JLabel zipcodeLabel2;
    private javax.swing.JTextField zipcodeTxt2;
    // End of variables declaration//GEN-END:variables
}
