/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videorentalstore.gui;

import videorentalstore.database.Database;

/**
 *
 * @author Ashley
 */
public class EmployeeAccount_SignUp extends javax.swing.JFrame {
    private Database db;
    /**
     * Creates new form EmployeeAccount_SignUp
     */
    public EmployeeAccount_SignUp(Database db) {
        initComponents();
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myEmployeeAccount = new javax.swing.JPanel();
        billingInfoPanel = new javax.swing.JPanel();
        MyEmployeeAccount = new javax.swing.JPanel();
        billingInfoLabel = new javax.swing.JLabel();
        billingInfoTxtPnel = new javax.swing.JPanel();
        addressTxt2 = new javax.swing.JTextField();
        creditCardExpLabel1 = new javax.swing.JLabel();
        creditCardExpirationMonth = new javax.swing.JComboBox();
        zipcodeTxt2 = new javax.swing.JTextField();
        creditCardImage = new javax.swing.JLabel();
        cityTxt2 = new javax.swing.JTextField();
        stateTxt2 = new javax.swing.JTextField();
        creditCardExpirationYear = new javax.swing.JComboBox();
        creditCardNumTxt2 = new javax.swing.JTextField();
        creditCardNumLabel2 = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        stateLabel2 = new javax.swing.JLabel();
        zipcodeLabel2 = new javax.swing.JLabel();
        cityLabel2 = new javax.swing.JLabel();
        personalInfoPanel = new javax.swing.JPanel();
        personalInfoLabelPanel = new javax.swing.JPanel();
        personalInfoLabel = new javax.swing.JLabel();
        personalInfoTxtPanel = new javax.swing.JPanel();
        newUserEmailTxt1 = new javax.swing.JTextField();
        newUserEmailLabel1 = new javax.swing.JLabel();
        birthdayDay = new javax.swing.JComboBox();
        lastNameLabel2 = new javax.swing.JLabel();
        firstNameTxt2 = new javax.swing.JTextField();
        birthdayLabel2 = new javax.swing.JLabel();
        newUserPasswordLabel1 = new javax.swing.JLabel();
        newUserPasswordTxt1 = new javax.swing.JPasswordField();
        newUsernameLabel1 = new javax.swing.JLabel();
        birthdayMonth = new javax.swing.JComboBox();
        birthdayYear = new javax.swing.JComboBox();
        firstNameLabel2 = new javax.swing.JLabel();
        newUsernameTxt1 = new javax.swing.JTextField();
        lastNameTxt2 = new javax.swing.JTextField();
        employeeRegistrationPanel = new javax.swing.JPanel();
        employeeRegistrationLabel = new javax.swing.JLabel();
        registerEmployeeAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myEmployeeAccount.setBackground(new java.awt.Color(255, 255, 255));

        billingInfoPanel.setForeground(new java.awt.Color(51, 51, 51));
        billingInfoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MyEmployeeAccount.setBackground(new java.awt.Color(204, 204, 204));

        billingInfoLabel.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        billingInfoLabel.setText("Payment & Billing Information");

        javax.swing.GroupLayout MyEmployeeAccountLayout = new javax.swing.GroupLayout(MyEmployeeAccount);
        MyEmployeeAccount.setLayout(MyEmployeeAccountLayout);
        MyEmployeeAccountLayout.setHorizontalGroup(
            MyEmployeeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyEmployeeAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billingInfoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MyEmployeeAccountLayout.setVerticalGroup(
            MyEmployeeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyEmployeeAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billingInfoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        creditCardExpLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        creditCardExpLabel1.setText("Credit Card Expiration Date:");

        creditCardExpirationMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        creditCardImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashley\\Desktop\\movieprojectphotos\\Image_CreditCards.png")); // NOI18N

        creditCardExpirationYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        creditCardNumLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        creditCardNumLabel2.setText("Credit Card Number: ");

        addressLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        addressLabel2.setText("Address:");

        stateLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        stateLabel2.setText("State:");

        zipcodeLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        zipcodeLabel2.setText("Zipcode:");

        cityLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        cityLabel2.setText("City:");

        javax.swing.GroupLayout billingInfoTxtPnelLayout = new javax.swing.GroupLayout(billingInfoTxtPnel);
        billingInfoTxtPnel.setLayout(billingInfoTxtPnelLayout);
        billingInfoTxtPnelLayout.setHorizontalGroup(
            billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingInfoTxtPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingInfoTxtPnelLayout.createSequentialGroup()
                        .addComponent(creditCardNumLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                                .addComponent(creditCardImage)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(creditCardNumTxt2)))
                    .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel2)
                            .addComponent(cityLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                                .addComponent(cityTxt2)
                                .addGap(18, 18, 18)
                                .addComponent(stateLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stateTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(zipcodeLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(zipcodeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                        .addComponent(creditCardExpLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(creditCardExpirationMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(creditCardExpirationYear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        billingInfoTxtPnelLayout.setVerticalGroup(
            billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingInfoTxtPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel2))
                .addGap(29, 29, 29)
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel2)
                    .addComponent(stateTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodeLabel2)
                    .addComponent(zipcodeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel2))
                .addGap(27, 27, 27)
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardNumLabel2)
                    .addComponent(creditCardNumTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(creditCardImage)
                .addGap(28, 28, 28)
                .addGroup(billingInfoTxtPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardExpirationMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditCardExpirationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditCardExpLabel1))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout billingInfoPanelLayout = new javax.swing.GroupLayout(billingInfoPanel);
        billingInfoPanel.setLayout(billingInfoPanelLayout);
        billingInfoPanelLayout.setHorizontalGroup(
            billingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyEmployeeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(billingInfoPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(billingInfoTxtPnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        billingInfoPanelLayout.setVerticalGroup(
            billingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingInfoPanelLayout.createSequentialGroup()
                .addComponent(MyEmployeeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billingInfoTxtPnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        personalInfoLabelPanel.setBackground(new java.awt.Color(204, 204, 204));

        personalInfoLabel.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        personalInfoLabel.setText("Personal Information");

        javax.swing.GroupLayout personalInfoLabelPanelLayout = new javax.swing.GroupLayout(personalInfoLabelPanel);
        personalInfoLabelPanel.setLayout(personalInfoLabelPanelLayout);
        personalInfoLabelPanelLayout.setHorizontalGroup(
            personalInfoLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalInfoLabel)
                .addContainerGap(1171, Short.MAX_VALUE))
        );
        personalInfoLabelPanelLayout.setVerticalGroup(
            personalInfoLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoLabelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personalInfoLabel)
                .addContainerGap())
        );

        newUserEmailLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        newUserEmailLabel1.setText("Email:");

        birthdayDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lastNameLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        lastNameLabel2.setText("Last Name:");

        birthdayLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        birthdayLabel2.setText("Birthday:");

        newUserPasswordLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        newUserPasswordLabel1.setText("Password:");

        newUsernameLabel1.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        newUsernameLabel1.setText("Username:");

        birthdayMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        birthdayYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "Item 2", "Item 3", "Item 4" }));

        firstNameLabel2.setFont(new java.awt.Font("Vani", 0, 15)); // NOI18N
        firstNameLabel2.setText("First Name:");

        javax.swing.GroupLayout personalInfoTxtPanelLayout = new javax.swing.GroupLayout(personalInfoTxtPanel);
        personalInfoTxtPanel.setLayout(personalInfoTxtPanelLayout);
        personalInfoTxtPanelLayout.setHorizontalGroup(
            personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(birthdayLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(birthdayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(birthdayDay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(birthdayYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newUserEmailLabel1)
                                    .addComponent(newUsernameLabel1))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoTxtPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(firstNameLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                .addComponent(firstNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastNameLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                                .addComponent(newUsernameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(newUserPasswordLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(newUserPasswordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newUserEmailTxt1))))
                .addContainerGap())
        );
        personalInfoTxtPanelLayout.setVerticalGroup(
            personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newUserPasswordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newUserPasswordLabel1))
                    .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newUsernameTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newUsernameLabel1)))
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoTxtPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(newUserEmailLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoTxtPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newUserEmailTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel2)
                    .addComponent(firstNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel2)
                    .addComponent(lastNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(personalInfoTxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayLabel2)
                    .addComponent(birthdayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout personalInfoPanelLayout = new javax.swing.GroupLayout(personalInfoPanel);
        personalInfoPanel.setLayout(personalInfoPanelLayout);
        personalInfoPanelLayout.setHorizontalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalInfoLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(personalInfoTxtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personalInfoPanelLayout.setVerticalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addComponent(personalInfoLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(personalInfoTxtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        employeeRegistrationLabel.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        employeeRegistrationLabel.setText("Employee Registration ");

        javax.swing.GroupLayout employeeRegistrationPanelLayout = new javax.swing.GroupLayout(employeeRegistrationPanel);
        employeeRegistrationPanel.setLayout(employeeRegistrationPanelLayout);
        employeeRegistrationPanelLayout.setHorizontalGroup(
            employeeRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeRegistrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeRegistrationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeeRegistrationPanelLayout.setVerticalGroup(
            employeeRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeRegistrationPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(employeeRegistrationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registerEmployeeAccount.setText("Register");
        registerEmployeeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmployeeAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myEmployeeAccountLayout = new javax.swing.GroupLayout(myEmployeeAccount);
        myEmployeeAccount.setLayout(myEmployeeAccountLayout);
        myEmployeeAccountLayout.setHorizontalGroup(
            myEmployeeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeRegistrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(myEmployeeAccountLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(myEmployeeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(852, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myEmployeeAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerEmployeeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(897, 897, 897))
        );
        myEmployeeAccountLayout.setVerticalGroup(
            myEmployeeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myEmployeeAccountLayout.createSequentialGroup()
                .addComponent(employeeRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(personalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(billingInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(registerEmployeeAccount)
                .addContainerGap(964, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myEmployeeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myEmployeeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerEmployeeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmployeeAccountActionPerformed
         dispose();
        EmployeeAccount f = new EmployeeAccount(db);
        f.setVisible(true);
    }//GEN-LAST:event_registerEmployeeAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAccount_SignUp(db).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MyEmployeeAccount;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JTextField addressTxt2;
    private javax.swing.JLabel billingInfoLabel;
    private javax.swing.JPanel billingInfoPanel;
    private javax.swing.JPanel billingInfoTxtPnel;
    private javax.swing.JComboBox birthdayDay;
    private javax.swing.JLabel birthdayLabel2;
    private javax.swing.JComboBox birthdayMonth;
    private javax.swing.JComboBox birthdayYear;
    private javax.swing.JLabel cityLabel2;
    private javax.swing.JTextField cityTxt2;
    private javax.swing.JLabel creditCardExpLabel1;
    private javax.swing.JComboBox creditCardExpirationMonth;
    private javax.swing.JComboBox creditCardExpirationYear;
    private javax.swing.JLabel creditCardImage;
    private javax.swing.JLabel creditCardNumLabel2;
    private javax.swing.JTextField creditCardNumTxt2;
    private javax.swing.JLabel employeeRegistrationLabel;
    private javax.swing.JPanel employeeRegistrationPanel;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JTextField firstNameTxt2;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JTextField lastNameTxt2;
    private javax.swing.JPanel myEmployeeAccount;
    private javax.swing.JLabel newUserEmailLabel1;
    private javax.swing.JTextField newUserEmailTxt1;
    private javax.swing.JLabel newUserPasswordLabel1;
    private javax.swing.JPasswordField newUserPasswordTxt1;
    private javax.swing.JLabel newUsernameLabel1;
    private javax.swing.JTextField newUsernameTxt1;
    private javax.swing.JLabel personalInfoLabel;
    private javax.swing.JPanel personalInfoLabelPanel;
    private javax.swing.JPanel personalInfoPanel;
    private javax.swing.JPanel personalInfoTxtPanel;
    private javax.swing.JButton registerEmployeeAccount;
    private javax.swing.JLabel stateLabel2;
    private javax.swing.JTextField stateTxt2;
    private javax.swing.JLabel zipcodeLabel2;
    private javax.swing.JTextField zipcodeTxt2;
    // End of variables declaration//GEN-END:variables
}
