

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videorentalstore.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import videorentalstore.User.User;
import videorentalstore.movies.Movie;
import videorentalstore.database.Database;
/**
 *
 * @author Ashley
 */
public class EmployeeAccount extends javax.swing.JFrame {
    private Database db;
    /**
     * Creates new form EmpolyeeAccount
     */
    public EmployeeAccount() {
        try {
            db = new Database("movies.db");
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        editDBTab = new javax.swing.JPanel();
        editBDPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        directorLabel = new javax.swing.JLabel();
        actorLabel = new javax.swing.JLabel();
        userRatingLabel = new javax.swing.JLabel();
        mpaarRatingLabel = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        directorTxt = new javax.swing.JTextField();
        actorTxt = new javax.swing.JTextField();
        userRatingTxt = new javax.swing.JTextField();
        mpaarRatingTxt = new javax.swing.JTextField();
        addMovieToDBButton = new javax.swing.JButton();
        movieClearnButton = new javax.swing.JButton();
        movieInfoLabel = new javax.swing.JLabel();
        movieDBTableScrollPane = new javax.swing.JScrollPane();
        movies = new javax.swing.JTable();
        editBDLabel = new javax.swing.JLabel();
        removeMovieFromDBButton = new javax.swing.JButton();
        editMovieInBDButon = new javax.swing.JButton();
        editDBLogoutButon = new javax.swing.JButton();
        editCustomerInfoTab = new javax.swing.JPanel();
        editCustomerInfoPanel = new javax.swing.JScrollPane();
        customerDBTable = new javax.swing.JTable();
        customerInfoPanel = new javax.swing.JPanel();
        customerInfoLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        birthdayTxt = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        zipcodeLabel = new javax.swing.JLabel();
        zipcodeTxt = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        creditCardNumLabel = new javax.swing.JLabel();
        creditCardNumTxt = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateTxt = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        creditCardExpireLabel = new javax.swing.JLabel();
        creditCardExpireDateTxt = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        customerClearButton = new javax.swing.JButton();
        addCustomerButton = new javax.swing.JButton();
        removeCustomerButton = new javax.swing.JButton();
        editCustomerButton = new javax.swing.JButton();
        editCustomerAccountLogoutButton = new javax.swing.JButton();
        editCustomerInformationLabel = new javax.swing.JLabel();
        rentMoviesTab = new javax.swing.JPanel();
        rentMoviesLogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editBDPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLabel.setText("Title:");

        directorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        directorLabel.setText("Director:");

        actorLabel.setText("Actor:");

        userRatingLabel.setText("User Rating:");

        mpaarRatingLabel.setText("MPAAR Rating:");

        addMovieToDBButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_AddButtonIcon.png"))); // NOI18N
        addMovieToDBButton.setText(" Add");
        addMovieToDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieToDBButtonActionPerformed(evt);
            }
        });

        movieClearnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_ClearButtonIcon.png"))); // NOI18N
        movieClearnButton.setText(" Clear");
        movieClearnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieClearnButtonActionPerformed(evt);
            }
        });

        movieInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        movieInfoLabel.setText("Movie Information");

        javax.swing.GroupLayout editBDPanelLayout = new javax.swing.GroupLayout(editBDPanel);
        editBDPanel.setLayout(editBDPanelLayout);
        editBDPanelLayout.setHorizontalGroup(
            editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(movieClearnButton)
                    .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(editBDPanelLayout.createSequentialGroup()
                            .addComponent(directorLabel)
                            .addGap(44, 44, 44)
                            .addComponent(directorTxt))
                        .addGroup(editBDPanelLayout.createSequentialGroup()
                            .addComponent(mpaarRatingLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mpaarRatingTxt))
                        .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieInfoLabel)
                            .addComponent(actorLabel)
                            .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(editBDPanelLayout.createSequentialGroup()
                                    .addComponent(userRatingLabel)
                                    .addGap(27, 27, 27)
                                    .addComponent(userRatingTxt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editBDPanelLayout.createSequentialGroup()
                                    .addComponent(titleLabel)
                                    .addGap(69, 69, 69)
                                    .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(actorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(titleTxt)))))
                        .addComponent(addMovieToDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        editBDPanelLayout.setVerticalGroup(
            editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieInfoLabel)
                .addGap(45, 45, 45)
                .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addGap(24, 24, 24)
                .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actorLabel)
                    .addComponent(actorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userRatingLabel)
                    .addComponent(userRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpaarRatingLabel)
                    .addComponent(mpaarRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(editBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(directorTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addMovieToDBButton)
                .addGap(18, 18, 18)
                .addComponent(movieClearnButton)
                .addGap(43, 43, 43))
        );

        movies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        movies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Some Movie", "Some Guy", "75", "PG-13", "Some Other Guy", "Yes"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MovieId", "title", "Actor", "User Rating", "MPAAR Rating", "Director", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        movies.setGridColor(new java.awt.Color(0, 0, 0));
        movies.getTableHeader().setReorderingAllowed(false);
        movies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviesMouseClicked(evt);
            }
        });
        movieDBTableScrollPane.setViewportView(movies);
        movies.getColumnModel().getColumn(0).setResizable(false);
        movies.getColumnModel().getColumn(1).setResizable(false);
        movies.getColumnModel().getColumn(2).setResizable(false);
        movies.getColumnModel().getColumn(3).setResizable(false);
        movies.getColumnModel().getColumn(4).setResizable(false);
        movies.getColumnModel().getColumn(5).setResizable(false);
        movies.getColumnModel().getColumn(6).setResizable(false);

        editBDLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        editBDLabel.setText("Edit Database");

        removeMovieFromDBButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_RemoveButtonIcon.png"))); // NOI18N
        removeMovieFromDBButton.setText("Delete");
        removeMovieFromDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMovieFromDBButtonActionPerformed(evt);
            }
        });

        editMovieInBDButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_EditButtonIcon.png"))); // NOI18N
        editMovieInBDButon.setText(" Edit");
        editMovieInBDButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMovieInBDButonActionPerformed(evt);
            }
        });

        editDBLogoutButon.setText("Logout");
        editDBLogoutButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDBLogoutButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDBTabLayout = new javax.swing.GroupLayout(editDBTab);
        editDBTab.setLayout(editDBTabLayout);
        editDBTabLayout.setHorizontalGroup(
            editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDBTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editDBTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editDBLogoutButon))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editDBTabLayout.createSequentialGroup()
                        .addGroup(editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editBDLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editDBTabLayout.createSequentialGroup()
                                .addComponent(editBDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editDBTabLayout.createSequentialGroup()
                                        .addComponent(editMovieInBDButon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(removeMovieFromDBButton))
                                    .addComponent(movieDBTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        editDBTabLayout.setVerticalGroup(
            editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDBTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editDBLogoutButon)
                .addGap(16, 16, 16)
                .addComponent(editBDLabel)
                .addGap(61, 61, 61)
                .addGroup(editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(movieDBTableScrollPane)
                    .addComponent(editBDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(editDBTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeMovieFromDBButton)
                    .addComponent(editMovieInBDButon))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Edit Database", editDBTab);

        customerDBTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "Username", "Password", "Email", "First Name", "Last Name", "Birthday", "Address", "City", "State", "Zipcode", "CreditCard Num", "Expiration Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editCustomerInfoPanel.setViewportView(customerDBTable);

        customerInfoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        customerInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        customerInfoLabel.setText("Customer Information");

        passwordLabel.setText("Password:");

        birthdayLabel.setText("Birthday:");

        lastNameLabel.setText("Last Name:");

        zipcodeLabel.setText("Zipcode:");

        addressLabel.setText("Address:");

        creditCardNumLabel.setText("Credit Card Number:");

        stateLabel.setText("State:");

        emailLabel.setText("Email:");

        creditCardExpireLabel.setText("Credit Card Exipration Date:");

        cityLabel.setText("City:");

        usernameLabel.setText("Username:");

        firstNameLabel.setText("First Name:");

        customerClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_ClearButtonIcon.png"))); // NOI18N
        customerClearButton.setText(" Clear");
        customerClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerClearButtonActionPerformed(evt);
            }
        });

        addCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_AddButtonIcon.png"))); // NOI18N
        addCustomerButton.setText(" Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(creditCardExpireLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creditCardExpireDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerClearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addComponent(creditCardNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creditCardNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(zipcodeLabel)
                            .addComponent(birthdayLabel)
                            .addComponent(emailLabel)
                            .addComponent(passwordLabel)
                            .addComponent(usernameLabel)
                            .addComponent(stateLabel)
                            .addComponent(cityLabel)
                            .addComponent(addressLabel))
                        .addGap(28, 28, 28)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailTxt)
                                .addComponent(birthdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zipcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordTxt)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addressLabel)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityLabel)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(stateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodeLabel)
                    .addComponent(zipcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditCardNumLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditCardExpireLabel)
                    .addComponent(creditCardExpireDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(addCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(customerClearButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout customerInfoPanelLayout = new javax.swing.GroupLayout(customerInfoPanel);
        customerInfoPanel.setLayout(customerInfoPanelLayout);
        customerInfoPanelLayout.setHorizontalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerInfoLabel)
                .addContainerGap(154, Short.MAX_VALUE))
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customerInfoPanelLayout.setVerticalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerInfoLabel)
                .addGap(18, 18, 18)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        removeCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_RemoveButtonIcon.png"))); // NOI18N
        removeCustomerButton.setText(" Remove");

        editCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_EditButtonIcon.png"))); // NOI18N
        editCustomerButton.setText(" Edit");

        editCustomerAccountLogoutButton.setText("Logout");
        editCustomerAccountLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerAccountLogoutButtonActionPerformed(evt);
            }
        });

        editCustomerInformationLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        editCustomerInformationLabel.setText("Edit Customer Information");

        javax.swing.GroupLayout editCustomerInfoTabLayout = new javax.swing.GroupLayout(editCustomerInfoTab);
        editCustomerInfoTab.setLayout(editCustomerInfoTabLayout);
        editCustomerInfoTabLayout.setHorizontalGroup(
            editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerInfoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editCustomerInfoTabLayout.createSequentialGroup()
                        .addGroup(editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editCustomerInfoTabLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editCustomerAccountLogoutButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editCustomerInfoTabLayout.createSequentialGroup()
                                .addComponent(customerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editCustomerInfoTabLayout.createSequentialGroup()
                                        .addComponent(editCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeCustomerButton)
                                        .addGap(0, 1124, Short.MAX_VALUE))
                                    .addComponent(editCustomerInfoPanel))))
                        .addGap(27, 27, 27))
                    .addGroup(editCustomerInfoTabLayout.createSequentialGroup()
                        .addComponent(editCustomerInformationLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        editCustomerInfoTabLayout.setVerticalGroup(
            editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerInfoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editCustomerAccountLogoutButton)
                .addGap(15, 15, 15)
                .addComponent(editCustomerInformationLabel)
                .addGap(61, 61, 61)
                .addGroup(editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCustomerInfoPanel))
                .addGap(18, 18, 18)
                .addGroup(editCustomerInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerButton)
                    .addComponent(removeCustomerButton))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Edit Customer Account", editCustomerInfoTab);

        rentMoviesLogoutButton.setText("Logout");
        rentMoviesLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentMoviesLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentMoviesTabLayout = new javax.swing.GroupLayout(rentMoviesTab);
        rentMoviesTab.setLayout(rentMoviesTabLayout);
        rentMoviesTabLayout.setHorizontalGroup(
            rentMoviesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentMoviesTabLayout.createSequentialGroup()
                .addContainerGap(1689, Short.MAX_VALUE)
                .addComponent(rentMoviesLogoutButton)
                .addContainerGap())
        );
        rentMoviesTabLayout.setVerticalGroup(
            rentMoviesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentMoviesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentMoviesLogoutButton)
                .addContainerGap(932, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Rent Movies", rentMoviesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>                        

    private void editCustomerAccountLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                                
        dispose();
    }                                                               

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();
        String email = emailTxt.getText();
        String firstName = firstNameTxt.getText();
        String lastName = lastNameTxt.getText();
        String birthday = birthdayTxt.getText();
        String city = cityTxt.getText();
        String state = stateTxt.getText();
        String zipCode = zipcodeTxt.getText();
        String address = addressTxt.getText();
        String creditCardNum = creditCardNumTxt.getText();
        String creditCardExpireDate = creditCardExpireDateTxt.getText();

    }                                                 

    private void customerClearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        usernameTxt.setText("");
        passwordTxt.setText("");
        emailTxt.setText("");
        firstNameTxt.setText("");
        lastNameTxt.setText("");
        birthdayTxt.setText("");
        cityTxt.setText("");
        stateTxt.setText("");
        zipcodeTxt.setText("");
        addressTxt.setText("");
        creditCardNumTxt.setText("");
        creditCardExpireDateTxt.setText("");
    }                                                   

    private void editDBLogoutButonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        dispose();
    }                                                 

    private void editMovieInBDButonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void removeMovieFromDBButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void moviesMouseClicked(java.awt.event.MouseEvent evt) {                                    
        try{
            int row = movies.getSelectedRow();
            String s = (movies.getModel().getValueAt(row,0).toString());
            String sql = "SELECT * FROM movies WHERE movieID=" + s;
//            pst = conn.prepareStatement(sql);
            /*
            ResultSet rs = db.executeQuery(sql);
            if(rs.next()){
                String add1 =rs.getString("title");
                titleTxt.setText(add1);
                
                String add2 =rs.getString("actor");
                actorTxt.setText(add2);
                
                String add3 =rs.getString("userRating");
                userRatingTxt.setText(add3);
                
                String add4 =rs.getString("mpaarRating");
                mpaarRatingTxt.setText(add4);
                
                String add5 =rs.getString("director");
                directorTxt.setText(add5);
            }
            */
            
        }catch(Exception e){
           System.out.println(e);
        }
    }                                   

    private void movieClearnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
//        titleTxt.setText("");
//        actorTxt.setText("");
//        userRatingTxt.setText("");
//        mpaarRatingTxt.setText("");
//        directorTxt.setText("");

    }                                                 

    private void addMovieToDBButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void rentMoviesLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        dispose();
    }                                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel actorLabel;
    private javax.swing.JTextField actorTxt;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addMovieToDBButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthdayTxt;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JTextField creditCardExpireDateTxt;
    private javax.swing.JLabel creditCardExpireLabel;
    private javax.swing.JLabel creditCardNumLabel;
    private javax.swing.JTextField creditCardNumTxt;
    private javax.swing.JButton customerClearButton;
    private javax.swing.JTable customerDBTable;
    private javax.swing.JLabel customerInfoLabel;
    private javax.swing.JPanel customerInfoPanel;
    private javax.swing.JLabel directorLabel;
    private javax.swing.JTextField directorTxt;
    private javax.swing.JLabel editBDLabel;
    private javax.swing.JPanel editBDPanel;
    private javax.swing.JButton editCustomerAccountLogoutButton;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JScrollPane editCustomerInfoPanel;
    private javax.swing.JPanel editCustomerInfoTab;
    private javax.swing.JLabel editCustomerInformationLabel;
    private javax.swing.JButton editDBLogoutButon;
    private javax.swing.JPanel editDBTab;
    private javax.swing.JButton editMovieInBDButon;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JButton movieClearnButton;
    private javax.swing.JScrollPane movieDBTableScrollPane;
    private javax.swing.JLabel movieInfoLabel;
    private javax.swing.JTable movies;
    private javax.swing.JLabel mpaarRatingLabel;
    private javax.swing.JTextField mpaarRatingTxt;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton removeCustomerButton;
    private javax.swing.JButton removeMovieFromDBButton;
    private javax.swing.JButton rentMoviesLogoutButton;
    private javax.swing.JPanel rentMoviesTab;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JLabel userRatingLabel;
    private javax.swing.JTextField userRatingTxt;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JLabel zipcodeLabel;
    private javax.swing.JTextField zipcodeTxt;
    // End of variables declaration                   
}